# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Program Files (x86)\Qt Designer\1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 504)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(800, 450))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.btn_Open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Open.setGeometry(QtCore.QRect(10, 450, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_Open.setFont(font)
        self.btn_Open.setObjectName("btn_Open")
        self.btn_Save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Save.setGeometry(QtCore.QRect(210, 450, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_Save.setFont(font)
        self.btn_Save.setObjectName("btn_Save")
        self.btn_Process = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Process.setGeometry(QtCore.QRect(410, 450, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_Process.setFont(font)
        self.btn_Process.setObjectName("btn_Process")
        self.btn_BackUp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_BackUp.setGeometry(QtCore.QRect(610, 450, 180, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btn_BackUp.setFont(font)
        self.btn_BackUp.setObjectName("btn_BackUp")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ПРОГРАММА"))
        self.btn_Open.setText(_translate("MainWindow", "Open"))
        self.btn_Save.setText(_translate("MainWindow", "Save"))
        self.btn_Process.setText(_translate("MainWindow", "Process"))
        self.btn_BackUp.setText(_translate("MainWindow", "BackUp"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
